version: "3.7"
services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    # Uncomment this volume section to persist the database to a local directory.
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: jobhopper_dev

  api:
    build: .
    volumes:
      - .:/app/
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: jobhopper_dev
      DB_HOST: db
      WAIT_HOSTS: db:5432
